#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99

validate_config() {
    uci_validate_section ifmqtoggle listener "${1}" \
        'enabled:bool:0' \
        'iface:string' \
        'mqtt_broker_host:string' \
        'mqtt_broker_port:uinteger' \
        'mqtt_broker_retry_delay:uinteger' \
        'mqtt_topic:string' \
        'mqtt_username:string' \
        'mqtt_password:string' \
        'mqtt_options:string'
}

init_listener() {
    instance=$1

    local enabled iface

    validate_config "$instance" || {
        echo "Invalid configuration for listener $instance"
        return 1
    }

    if [ "$enabled" = 0 ]; then
        echo "Listener $instance is disabled"
        return
    fi
    echo "Starting listener $instance for network interface $iface"

    procd_open_instance

    procd_set_param command /usr/bin/ifmqtoggle "$instance"
    procd_set_param file /etc/config/ifmqtoggle
    procd_set_param stdout 1
    procd_set_param stderr 1

    procd_close_instance
}

start_service() {
    config_load 'ifmqtoggle'
    config_foreach init_listener 'listener'
}

reload_service() {
    stop
    start
}
